steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/hiral-yadav/google-cloud.git']
    dir: 'app'
  - name: 'gcr.io/cloud-builders/git'
    args: ['checkout', 'main']
    dir: 'app'
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
    dir: 'app'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/storage-app', '.']
#    dir: 'app'

